import React from 'react';
import styles from '../docsContent.module.css';
import { DocsCallout, DocsImage, DocsNav, DocsFAQ, DocsFAQItem } from '../../../components/Docs/DocsUI';

export const metadata = {
    title: 'Promotion Plans & Marketing | HUBly Docs',
    description: 'Discover how HUBly’s algorithm-driven Promotion Plans can skyrocket your software’s visibility and sales.',
    url: 'https://www.hubly-tools.com/docs/promotions'
};

export default function DocsPage() {
    return (
        <article className={styles.article}>
            <h1>Promotion Plans & Marketing</h1>
            <p>
                Organic growth is excellent, but when you are ready to scale aggressively, you need guaranteed visibility. 
                HUBly's <strong>Promotion Engine</strong> is designed to place your software directly in front of high-intent buyers exactly when they are searching for a solution in your category.
            </p>

            <DocsImage 
                src="/docs-promote-plans.png" 
                alt="Promotions Dashboard" 
                caption="Select from strictly curated promotion tiers to dominate your category. Payments secured by LemonSqueezy." 
            />

            <h2>1. Available Promotion Tiers</h2>
            <p>
                We offer three distinct tiers of promotion to match your marketing budget and scale. Every plan provides instant activation upon secure payment.
            </p>

            <h3>The "Featured" Plan ($49/mo)</h3>
            <p>
                Our most popular tier, designed for startups and solo-founders looking for immediate traction.
            </p>
            <ul>
                <li><strong>Homepage Hero Slot:</strong> Your tool enters the rotation on the main HUBly homepage for 30 days.</li>
                <li><strong>Priority Category Ranking:</strong> When users filter by your specific category (e.g., "SEO Tools"), your software is pinned to the top of the results.</li>
                <li><strong>Verified Tool Badge:</strong> A distinctive blue "Featured" badge is applied to your Tool Card across the entire site, increasing click-through rates.</li>
                <li><strong>Newsletter Spotlight:</strong> Inclusion in our weekly community newsletter sent to thousands of professionals.</li>
            </ul>

            <h3>The "Market Authority" Plan ($149/mo)</h3>
            <p>
                Built for established SaaS companies seeking ultimate visibility and long-term SEO benefits.
            </p>
            <ul>
                <li><strong>Everything in Featured, plus:</strong></li>
                <li><strong>Maximum Priority Status:</strong> Top placement in Global Search results for 30 days.</li>
                <li><strong>Do-Follow Backlink (SEO):</strong> A high-authority backlink directly from your HUBly profile to boost your domain authority on Google while the promotion is active.</li>
                <li><strong>Site-wide Banner Ads:</strong> Your tool will occasionally appear in the Smart Banners located on sidebars and article pages.</li>
                <li><strong>Dedicated Review Article:</strong> Our editorial team will write a comprehensive, unbiased breakdown of your tool to drive organic traffic.</li>
            </ul>

            <h3>Custom / Agency Plan (Contact Sales)</h3>
            <p>
                For marketing agencies managing multiple clients or enterprises needing bespoke placements. This unlocks bulk tool submissions, custom ad placements, white-glove onboarding, and a dedicated account manager.
            </p>

            <DocsCallout type="tip" title="Transparent ROI Tracking">
                <p>
                    We do not believe in "black box" marketing. Every click and view generated by your Promotion Plan is tracked in real-time on your <strong>Maker Dashboard</strong>, allowing you to calculate your exact Return on Investment (ROI).
                </p>
            </DocsCallout>

            <h2>2. Quality Control Standards</h2>
            <p>
                To protect our users, <strong>money cannot buy a good rating</strong>. Purchasing a Promotion Plan guarantees impressions and visibility, but it does not alter your Community Rating or Expert Verdict. If a promoted tool has a 2-star rating from the community, it will be promoted with a 2-star rating. We strictly advise Founders to ensure their software is polished and responsive to user feedback before investing in traffic.
            </p>

            
            
            <DocsFAQ>
                <DocsFAQItem question="When does my promotion start?">
                    Immediately. The moment your transaction is cleared through LemonSqueezy, our algorithms instantly inject your tool into the Featured rotation and apply the Verified badges.
                </DocsFAQItem>
                <DocsFAQItem question="Can I upgrade from Featured to Market Authority?">
                    Yes. You can upgrade your plan at any time from your Maker Dashboard. The remaining pro-rated value of your current plan will be automatically deducted from the upgrade cost.
                </DocsFAQItem>
                <DocsFAQItem question="Do I get a refund if I don't get enough clicks?">
                    No. Promotion Plans guarantee visibility and impressions (which are tracked in your dashboard), but they cannot guarantee clicks or conversions. It is your responsibility to ensure your tool's description and pricing are attractive to buyers.
                </DocsFAQItem>
            </DocsFAQ>
            
            <DocsNav 
                prev={{ title: "Edit & Manage", href: "/docs/edit" }}
                next={{ title: "Premium Memberships", href: "/docs/premium" }}
            />
        </article>
    );
}
